version: 0.0
os: linux
files:
  - source: /
    destination: /home/bitnami/htdocs/nutrition-table
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: codedeploy-hooks/after_install.sh
      timeout: 3600
      runas: root
  # ApplicationStart:
  #   - location: 
