export const formDataEU = [
  {
    name: "Fat",
    per100g: "9.2",
    perportion: "8",
    unit: "Grams",
    bold: "No",
    leftSpacing: "0",
    order: "",
    RI: "10",
  },
  {
    name: "Of which Saturates",
    per100g: "5.6",
    perportion: "3.7",
    unit: "Grams",
    bold: "Yes",
    leftSpacing: "0",
    order: "",
    RI: "10",
  },
  {
    name: "Carbohydrate",
    per100g: "46",
    perportion: "9",
    unit: "Grams",
    bold: "Yes",
    leftSpacing: "0",
    order: "",
    RI: "10",
  },
  {
    name: "Of which Sugars",
    per100g: "21",
    perportion: "8",
    unit: "Grams",
    bold: "Yes",
    leftSpacing: "0",
    order: "",
    RI: "10",
  },
  {
    name: "Protein",
    per100g: "5.0",
    perportion: "2.7",
    unit: "Grams",
    bold: "Yes",
    leftSpacing: "0",
    order: "",
    RI: "10",
  },
  {
    name: "Salt",
    per100g: "0.2",
    perportion: "0.11",
    unit: "Grams",
    bold: "Yes",
    leftSpacing: "0",
    order: "",
    RI: "10",
  },
];
export const formDataNA = [
  {
    name: "Total Fat",
    quantity: "8",
    unit: "Grams",
    dailyValue: "10",
    bold: "Yes",
    order: "",
    leftSpacing: "",
    preparedProductQuantity: "",
    preparedProductDV: "",
    preparedProductUnit: "Grams",
  },
  {
    name: "Saturated Fat",
    quantity: "1",
    unit: "Grams",
    dailyValue: "5",
    bold: "No",
    order: "",
    leftSpacing: "1",
    preparedProductQuantity: "",
    preparedProductDV: "",
    preparedProductUnit: "Grams",
  },
  {
    name: "Trans Fat",
    quantity: "0",
    unit: "MilliGrams",
    dailyValue: "",
    bold: "No",
    order: "",
    leftSpacing: "1",
    preparedProductQuantity: "",
    preparedProductDV: "",
    preparedProductUnit: "Grams",
  },
  {
    name: "Cholesterol",
    quantity: "0",
    unit: "MilliGrams",
    dailyValue: "0",
    bold: "No",
    order: "",
    leftSpacing: "",
    preparedProductQuantity: "",
    preparedProductDV: "",
    preparedProductUnit: "Grams",
  },
  {
    name: "Sodium ",
    quantity: "160",
    unit: "Milligrams",
    dailyValue: "7",
    bold: "No",
    order: "",
    leftSpacing: "",
    preparedProductQuantity: "",
    preparedProductDV: "",
    preparedProductUnit: "Grams",
  },
  {
    name: "Total Carbohydrate",
    quantity: "37",
    unit: "Grams",
    dailyValue: "13",
    bold: "No",
    order: "",
    leftSpacing: "",
    preparedProductQuantity: "",
    preparedProductDV: "",
    preparedProductUnit: "Grams",
  },
  {
    name: "Dietary Fiber",
    quantity: "4",
    unit: "Grams",
    dailyValue: "14",
    bold: "No",
    order: "",
    leftSpacing: "1",
    preparedProductQuantity: "",
    preparedProductDV: "",
    preparedProductUnit: "Grams",
  },
  {
    name: "Total Sugars",
    quantity: "12",
    unit: "Grams",
    dailyValue: "",
    bold: "No",
    order: "",
    leftSpacing: "",
    preparedProductQuantity: "",
    preparedProductDV: "",
    preparedProductUnit: "Grams",
  },
  {
    name: "Includes Added Sugars",
    quantity: "10",
    unit: "Grams",
    dailyValue: "20",
    bold: "No",
    order: "",
    leftSpacing: "2",
    preparedProductQuantity: "",
    preparedProductDV: "",
    preparedProductUnit: "Grams",
  },
  {
    name: "Protein",
    quantity: "3",
    unit: "Grams",
    dailyValue: "10",
    bold: "Yes",
    order: "",
    leftSpacing: "",
    preparedProductQuantity: "",
    preparedProductDV: "",
    preparedProductUnit: "Grams",
  },
];
export const formDataCA = [
  {
    name: "Fat / Lipides",
    quantity: "0",
    Unit: "Grams",
    dailyValue: "0",
    bold: "Yes",
    order: "",
    leftSpacing: "",
    preparedProduct: "5",
  },
  {
    name: "Saturated / saturés",
    quantity: "0",
    Unit: "Grams",
    dailyValue: "0",
    bold: "Yes",
    order: "",
    leftSpacing: "",
    preparedProduct: "5",
  },
  {
    name: "+ Trans / trans",
    quantity: "0",
    Unit: "Grams",
    dailyValue: "",
    bold: "Yes",
    order: "",
    leftSpacing: "",
    preparedProduct: "5",
  },
  {
    name: "Carbohydrate / Glucid",
    quantity: "26",
    Unit: "Grams",
    dailyValue: "",
    bold: "Yes",
    order: "",
    leftSpacing: "",
    preparedProduct: "5",
  },
  {
    name: "Fibre & Fibres",
    quantity: "0",
    Unit: "Grams",
    dailyValue: "0",
    bold: "Yes",
    order: "",
    leftSpacing: "",
    preparedProduct: "5",
  },
  {
    name: "Sugars / sucres",
    quantity: "22",
    Unit: "Grams",
    dailyValue: "22",
    bold: "Yes",
    order: "",
    leftSpacing: "",
    preparedProduct: "5",
  },
  {
    name: "Protein / Protéines",
    quantity: "2",
    Unit: "Grams",
    dailyValue: "",
    bold: "Yes",
    order: "",
    leftSpacing: "",
    preparedProduct: "5",
  },
  {
    name: "Cholesterol / Cholest",
    quantity: "0",
    Unit: "Grams",
    dailyValue: "",
    bold: "Yes",
    order: "",
    leftSpacing: "",
    preparedProduct: "5",
  },
  {
    name: "Sodium",
    quantity: "0",
    Unit: "Grams",
    dailyValue: "0",
    bold: "Yes",
    order: "",
    leftSpacing: "",
    preparedProduct: "5",
  },
];

export const vitaminsEU = [
  {
    name: "Vitamin C",
    per100g: "14.81",
    perportion: "4.5",
    LeftSpacing: "",
    order: "",
    RI: "",
    unit: "Grams",
  },
];
export const mineralsEU = [];
export const vitaminsNA = [
  {
    name: "Vitamin D",
    quantity: "2",
    dailyValue: "10",
    LeftSpacing: "",
    order: "",
    RI: "",
    unit: "Micrograms",
  },
];
export const mineralsNA = [
  {
    name: "Calcium",
    quantity: "260",
    dailyValue: "20",
    LeftSpacing: "",
    order: "",
    RI: "",
    unit: "Miligrams",
  },
  {
    name: "Vitamin D",
    quantity: "8",
    dailyValue: "45",
    LeftSpacing: "",
    order: "",
    RI: "",
    unit: "Miligrams",
  },
  {
    name: "Vitamin D",
    quantity: "240",
    dailyValue: "6",
    LeftSpacing: "",
    order: "",
    RI: "",
    unit: "Miligrams",
  },
];
export const vitaminsCA = [];
export const mineralsCA = [
  {
    name: "Potassium",
    quantity: "450",
    dailyValue: "10",
    LeftSpacing: "",
    order: "",
    RI: "",
    unit: "Miligrams",
  },
  {
    name: "Calcium",
    quantity: "30",
    dailyValue: "2",
    LeftSpacing: "",
    order: "",
    RI: "",
    unit: "Miligrams",
  },
  {
    name: "Iron / Fer",
    quantity: "0",
    dailyValue: "0",
    LeftSpacing: "",
    order: "",
    RI: "",
    unit: "Miligrams",
  },
];
