name: Deployment with AWS CodeDeploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Generate artifact name
        id: artifact
        run: |
          echo "ARTIFACT_NAME=artifact-$(date +%Y%m%d%H%M%S).zip" >> $GITHUB_ENV
      - name: Zip and upload to S3
        run: |
          zip -r ${{ env.ARTIFACT_NAME }} ./* appspec.yml
          aws s3 cp ${{ env.ARTIFACT_NAME }} s3://nutrition-table-deployment-artifacts/${{ env.ARTIFACT_NAME }}
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: your-aws-region
      # - name: Create and monitor deployment
      #   id: deploy
      #   run: |
      #     DEPLOYMENT_ID=$(aws deploy create-deployment \
      #       --application-name your-codedeploy-app-name \
      #       --deployment-config-name CodeDeployDefault.OneAtATime \
      #       --deployment-group-name your-deployment-group-name \
      #       --s3-location bucket=your-s3-bucket,key=${{ env.ARTIFACT_NAME }},bundleType=zip \
      #       --output text --query 'deploymentId')
      #     echo "Deployment ID: $DEPLOYMENT_ID"
      # aws deploy wait deployment-successful --deployment-id $DEPLOYMENT_I
