name: Deployment with AWS CodeDeploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - name: Install specific Yarn version
        run: npm install -g yarn@1.22.18
      - name: Install requirements
        run: yarn install
      - name: Generate artifact name
        id: artifact
        run: |
          echo "ARTIFACT_NAME=artifact-$(date +%Y-%m-%d).zip" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Zip and upload the artifact to S3
        run: |
          zip -r ${{ env.ARTIFACT_NAME }} ./*
          aws s3 cp ${{ env.ARTIFACT_NAME }} s3://nutrition-table-deployment-artifacts/${{ env.ARTIFACT_NAME }}
      - name: Create and monitor deployment
        id: deploy
        run: |
          DEPLOYMENT_ID=$(aws deploy create-deployment \
            --application-name nutrition-table-app \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name nutrition-table-app \
            --s3-location bucket=nutrition-table-deployment-artifacts,key=${{ env.ARTIFACT_NAME }},bundleType=zip \
            --output text --query 'deploymentId')
          echo "Deployment ID: $DEPLOYMENT_ID"
      # aws deploy wait deployment-successful --deployment-id $DEPLOYMENT_I
