name: Deployment to STAGE (with AWS CodeDeploy)

on:
  push:
    branches:
      - stage
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - name: Install dependencies
        run: npm install
      - name: Create .env file
        run: |
          echo "SHOPIFY_API_KEY=12782b4542e3e6e249ab54cda51c4669" >> .env
          echo "SHOPIFY_API_SECRET=81a57add137002b088873613db0ca069" >> .env
          echo "SHOP=nutritiontable.myshopify.com" >> .env
          echo "SCOPES=write_products,read_products" >> .env
          echo "HOST=https://nutrition-table.dev.cronum.app/" >> .env
          echo "MONGO_DB_URL=mongodb://localhost:27017/nutritiontable" >> .env
          # echo "SHOPIFY_API_KEY=${{ secrets.SHOPIFY_API_KEY }}" >> .env
          # echo "SHOPIFY_API_SECRET=${{ secrets.SHOPIFY_API_SECRET }}" >> .env
          # echo "SHOP=${{ secrets.SHOP }}" >> .env
          # echo "SCOPES=${{ secrets.SCOPES }}" >> .env
          # echo "HOST=${{ secrets.HOST }}" >> .env
          # echo "MONGO_DB_URL=${{ secrets.MONGO_DB_URL }}" >> .env
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Remove node_modules folder
        run: rm -rf node_modules
      - name: Generate artifact name
        id: artifact
        run: |
          echo "ARTIFACT_NAME=staging-artifact-$(date +%Y-%m-%d).zip" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Zip and upload the artifact to S3
        run: |
          zip -r ${{ env.ARTIFACT_NAME }} ./*
          aws s3 cp ${{ env.ARTIFACT_NAME }} s3://nutrition-table-deployment-artifacts/${{ env.ARTIFACT_NAME }}
      - name: Create and monitor deployment
        id: deploy
        run: |
          DEPLOYMENT_ID=$(aws deploy create-deployment \
            --application-name nutrition-table-app \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name staging-nutrition-table \
            --s3-location bucket=nutrition-table-deployment-artifacts,key=${{ env.ARTIFACT_NAME }},bundleType=zip \
            --output text --query 'deploymentId')
          echo "Deployment ID: $DEPLOYMENT_ID"
      # aws deploy wait deployment-successful --deployment-id $DEPLOYMENT_I
